// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPi9D0LHEYxo-on7fglVrECTMXQezng5w',
    appId: '1:856393800795:web:8b2dba6850de4e07e4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    authDomain: 'ramstech-esp32.firebaseapp.com',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
    measurementId: 'G-P4BSQCYMNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1tZA7ZBaR8n5ApHW97Swq1q8tVJNbfQ',
    appId: '1:856393800795:android:5e8c3382a7f923eae4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSHfgD4JquDD7Cenyyfsw3bjZQWxVT5I',
    appId: '1:856393800795:ios:e889da0c0b8c5507e4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
    iosBundleId: 'com.example.ramstech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSHfgD4JquDD7Cenyyfsw3bjZQWxVT5I',
    appId: '1:856393800795:ios:e889da0c0b8c5507e4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
    iosBundleId: 'com.example.ramstech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPi9D0LHEYxo-on7fglVrECTMXQezng5w',
    appId: '1:856393800795:web:c1c5900170001fb1e4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    authDomain: 'ramstech-esp32.firebaseapp.com',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
    measurementId: 'G-PMCXPVC5FK',
  );
}
