// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPi9D0LHEYxo-on7fglVrECTMXQezng5w',
    appId: '1:856393800795:web:2d186b9cf3c9986ae4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    authDomain: 'ramstech-esp32.firebaseapp.com',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
    measurementId: 'G-HQB220705G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1tZA7ZBaR8n5ApHW97Swq1q8tVJNbfQ',
    appId: '1:856393800795:android:021627829c70e065e4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSHfgD4JquDD7Cenyyfsw3bjZQWxVT5I',
    appId: '1:856393800795:ios:0e91a9d772434bb6e4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
    androidClientId: '856393800795-fnji7b7f4srnqevmdjot400cqtd250q2.apps.googleusercontent.com',
    iosClientId: '856393800795-dd2t0udeise812rncg797huir9omkc3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ramstech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSHfgD4JquDD7Cenyyfsw3bjZQWxVT5I',
    appId: '1:856393800795:ios:0e91a9d772434bb6e4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
    androidClientId: '856393800795-fnji7b7f4srnqevmdjot400cqtd250q2.apps.googleusercontent.com',
    iosClientId: '856393800795-dd2t0udeise812rncg797huir9omkc3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ramstech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPi9D0LHEYxo-on7fglVrECTMXQezng5w',
    appId: '1:856393800795:web:a454d5f5a3598dcbe4737e',
    messagingSenderId: '856393800795',
    projectId: 'ramstech-esp32',
    authDomain: 'ramstech-esp32.firebaseapp.com',
    databaseURL: 'https://ramstech-esp32-default-rtdb.firebaseio.com',
    storageBucket: 'ramstech-esp32.firebasestorage.app',
    measurementId: 'G-2Q2PM7YQEM',
  );

}